/**
 * E2E Test Configuration
 * 
 * Centralized constants for E2E tests to avoid hardcoding schema-driven values.
 * 
 * IMPORTANT - Variable Naming Convention:
 * - Variable names (left side): SCondition Group/original names (e.g., CONDITION, CONDITION_GROUP)
 * - String values (right side): Current schema values (e.g., 'Condition', 'Condition Group')
 * 
 * This allows schema values to change without breaking test logic.
 * When schema changes, only update the values here.
 * 
 * NOTE: Display names in rule structure (like "Condition", "Condition Group") are
 * generated by the naming system and should be checked using literal strings in tests,
 * NOT these config values. These RULE_TYPES values are ONLY for selecting rule types
 * in dropdowns.
 */

/**
 * Rule Type Values for Dropdown Selections
 * These must match the ruleType enum values in the schema
 */
export const RULE_TYPES = {
  CONDITION: 'Condition',              // Condition rules (boolean-returning)
  CONDITION_GROUP: 'Condition Group',        // Condition group rules (boolean-returning)
  LIST: 'List',           // List rules (array-returning)
  REPORTING: 'Reporting',
  TRANSFORMATION: 'Transformation',
  AGGREGATION: 'Aggregation',
  VALIDATION: 'Validation'
};

/**
 * Structure Types
 * These are NOT schema-driven - they are part of the rule definition structure
 * and should remain as-is even if ruleType values change
 */
export const STRUCTURE_TYPES = {
  CONDITION: 'condition',
  EXPRESSION: 'expression'
};
